version: '3'

services:

  # 数据库管理
  adminer:
    image: adminer
    #build: ./adminer
    #depends_on:
    #  - php-fpm
    volumes:
      - ./adminer/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - ${DB_ADMINER_PORT}:8080

  # php-fpm
  php-fpm:
    build: ./php-fpm
    image: docker-laravel-php-fpm
    depends_on:
      - db
      - redis
    volumes:
      - ${APPLICATION}:/var/www/html:cached
    environment:
      - CHANGE_SOURCE=${CHANGE_SOURCE}

  # php-worker，执行队列等
  worker:
    build: ./php-worker
    depends_on:
      - php-fpm
    restart: ${CONTAINER_RESTART}
    volumes:
      - ${APPLICATION}:/var/www/html:cached

  # php-worker，执行队列等
  cron:
    build: ./cron
    depends_on:
      - php-fpm
    restart: ${CONTAINER_RESTART}
    volumes:
      - ${APPLICATION}:/var/www/html:cached

  # php-composer，安装组键、发布到服务器等操作
  workspace:
    build: ./workspace
    depends_on:
      - php-fpm
    environment:
      - CHANGE_SOURCE=${CHANGE_SOURCE}
    volumes:
      - ${APPLICATION}:/var/www/html:cached
      - ~/.ssh/:/root/.ssh/:cached
    tty: true
    

  # nginx
  web:
    image: nginx:alpine
    depends_on:
      - php-fpm
    volumes:
      - ${APPLICATION}:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"

  # redis
  redis:
    #build: ./redis
    image: redis:4-alpine
    restart: ${CONTAINER_RESTART}

  # db 因为 postgres 镜像小，同时laravel完全支持，所以选择了这个数据库
  db:
    image: postgres:10-alpine
    restart: ${CONTAINER_RESTART}
    volumes:
      - ${APPLICATION}:/var/www/html:cached
      - ${DB_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata

